version: '3'
services:
  nodejs-server:
    build:
      context: ./api
    ports:
      - "4242:4242"
    container_name: node-api
    volumes:
       - ./api:/usr/src/app/api
       - /usr/src/app/api/node_modules
  react-ui:
    build:
      context: ./app
    ports:
      - "5173:5173"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./app:/usr/src/app/my-app
       - /usr/src/app/my-app/node_modules